// This file was autogenerated from $current_file. DO NOT EDIT.

\#pragma once

\#include <vulkan/vulkan.h>

namespace cvk
{

#foreach ($create_info in $create_infos)
#parse("CreateInfo.tpl")
#end

} // namespace cvk